"""ROB-512 갭3: yfinance sector/industry 영문 → 한글 표시명 정적 매핑.

표시용 베스트에포트 사전이다. 미스는 None — 호출자가 영문 원문을 그대로
표시한다(fake 한글 금지). 항목 추가는 자유(additive)다.
"""

from __future__ import annotations

# yfinance info["sector"] — 11종 전체
_SECTOR_KR: dict[str, str] = {
    "Technology": "기술",
    "Healthcare": "헬스케어",
    "Financial Services": "금융",
    "Consumer Cyclical": "임의소비재",
    "Consumer Defensive": "필수소비재",
    "Industrials": "산업재",
    "Energy": "에너지",
    "Utilities": "유틸리티",
    "Real Estate": "부동산",
    "Basic Materials": "소재",
    "Communication Services": "커뮤니케이션서비스",
}

# yfinance info["industry"] — 빈출 항목 (전수 아님; 미스는 영문 표시)
_INDUSTRY_KR: dict[str, str] = {
    "Semiconductors": "반도체",
    "Semiconductor Equipment & Materials": "반도체장비·소재",
    "Software - Application": "응용소프트웨어",
    "Software - Infrastructure": "인프라소프트웨어",
    "Consumer Electronics": "가전·전자기기",
    "Computer Hardware": "컴퓨터하드웨어",
    "Communication Equipment": "통신장비",
    "Information Technology Services": "IT서비스",
    "Electronic Components": "전자부품",
    "Internet Content & Information": "인터넷콘텐츠·정보",
    "Internet Retail": "인터넷쇼핑",
    "Entertainment": "엔터테인먼트",
    "Telecom Services": "통신서비스",
    "Advertising Agencies": "광고",
    "Electronic Gaming & Multimedia": "게임·멀티미디어",
    "Drug Manufacturers - General": "제약(대형)",
    "Drug Manufacturers - Specialty & Generic": "제약(스페셜티·제네릭)",
    "Biotechnology": "바이오테크",
    "Medical Devices": "의료기기",
    "Medical Instruments & Supplies": "의료기구·소모품",
    "Diagnostics & Research": "진단·연구",
    "Medical Care Facilities": "의료서비스시설",
    "Healthcare Plans": "건강보험",
    "Banks - Diversified": "대형은행",
    "Banks - Regional": "지방은행",
    "Capital Markets": "자본시장",
    "Asset Management": "자산운용",
    "Insurance - Diversified": "종합보험",
    "Insurance - Life": "생명보험",
    "Insurance - Property & Casualty": "손해보험",
    "Credit Services": "신용서비스",
    "Financial Data & Stock Exchanges": "금융데이터·거래소",
    "Auto Manufacturers": "자동차",
    "Auto Parts": "자동차부품",
    "Restaurants": "외식",
    "Apparel Retail": "의류소매",
    "Footwear & Accessories": "신발·액세서리",
    "Travel Services": "여행서비스",
    "Resorts & Casinos": "리조트·카지노",
    "Lodging": "호텔",
    "Specialty Retail": "전문소매",
    "Home Improvement Retail": "홈임프루브먼트소매",
    "Discount Stores": "할인점",
    "Grocery Stores": "식료품점",
    "Household & Personal Products": "생활용품",
    "Beverages - Non-Alcoholic": "음료(비주류)",
    "Beverages - Brewers": "맥주",
    "Beverages - Wineries & Distilleries": "주류(와인·증류)",
    "Confectioners": "제과",
    "Packaged Foods": "포장식품",
    "Tobacco": "담배",
    "Aerospace & Defense": "항공우주·방산",
    "Railroads": "철도",
    "Airlines": "항공사",
    "Farm & Heavy Construction Machinery": "농기계·중장비",
    "Specialty Industrial Machinery": "산업기계",
    "Electrical Equipment & Parts": "전기장비·부품",
    "Building Products & Equipment": "건축자재·설비",
    "Engineering & Construction": "엔지니어링·건설",
    "Waste Management": "폐기물처리",
    "Integrated Freight & Logistics": "종합물류",
    "Trucking": "트럭운송",
    "Marine Shipping": "해운",
    "Oil & Gas Integrated": "종합석유가스",
    "Oil & Gas E&P": "석유가스탐사·생산",
    "Oil & Gas Midstream": "석유가스미드스트림",
    "Oil & Gas Refining & Marketing": "정유·판매",
    "Oil & Gas Equipment & Services": "유전장비·서비스",
    "Utilities - Regulated Electric": "전력(규제)",
    "Utilities - Regulated Gas": "가스(규제)",
    "Utilities - Renewable": "신재생유틸리티",
    "REIT - Diversified": "리츠(복합)",
    "REIT - Residential": "리츠(주거)",
    "REIT - Retail": "리츠(리테일)",
    "REIT - Industrial": "리츠(산업)",
    "REIT - Specialty": "리츠(특수)",
    "REIT - Healthcare Facilities": "리츠(헬스케어)",
    "Real Estate Services": "부동산서비스",
    "Gold": "금",
    "Copper": "구리",
    "Steel": "철강",
    "Aluminum": "알루미늄",
    "Chemicals": "화학",
    "Specialty Chemicals": "정밀화학",
    "Agricultural Inputs": "농자재",
    "Solar": "태양광",
}


def korean_sector_label(value: str | None) -> str | None:
    """industry/sector 영문 원문 → 한글 표시명. 미스/빈 값은 None."""
    if not value:
        return None
    return _INDUSTRY_KR.get(value) or _SECTOR_KR.get(value)
