"""Task #1173 — deterministic KR scenarios for the KR-block golden.

``kr_scenarios(module)`` drives a ``kis_lots`` module through its pre-#1173
public API only (no ``market`` argument, ``LedgerFill`` without ``venue``), so
the same function renders the golden from the pre-change module and the
comparison from the current one. The golden file was generated by running it
against ``origin/main``'s ``app/services/execution_ledger/kis_lots.py`` at
f24eb3a7f, before the US extension existed.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime, timedelta
from decimal import Decimal
from pathlib import Path
from types import ModuleType
from typing import Any

GOLDEN_PATH = Path(__file__).with_name("kis_lots_kr_blocks_golden.json")

# 2026-09-29 14:30 KST
NOW = datetime(2026, 9, 29, 5, 30, tzinfo=UTC)
TODAY = datetime(2026, 9, 29, 0, 30, tzinfo=UTC)  # 09:30 KST
YESTERDAY = NOW - timedelta(days=1)
SEED_AT = datetime(2026, 9, 1, tzinfo=UTC)


def _fills(m: ModuleType, *rows: tuple[Any, ...]) -> list[Any]:
    out = []
    for i, (side, qty, price, at, source, order) in enumerate(rows, start=1):
        out.append(
            m.LedgerFill(
                id=i,
                source=source,
                side=side,
                quantity=Decimal(qty),
                price=Decimal(price),
                filled_at=at,
                broker_order_id=order,
            )
        )
    return out


def _orders(m: ModuleType, *rows: tuple[Any, ...]) -> list[Any]:
    return [
        m.OrderRow(
            id=i,
            order_no=order_no,
            status=status,
            quantity=None if qty is None else Decimal(qty),
            price=Decimal("70000"),
            trade_date=at,
            side=side,
        )
        for i, (order_no, status, qty, at, side) in enumerate(rows, start=1)
    ]


def kr_scenarios(m: ModuleType) -> dict[str, Any]:
    fresh = m.Freshness("fresh", NOW - timedelta(minutes=10), 10.0)
    stale = m.Freshness("stale", NOW - timedelta(hours=5), 300.0)
    missing = m.Freshness("missing", None, None)
    base = _fills(
        m,
        ("buy", "10", "65000", SEED_AT, "manual_import", "SEED-20260901-196170"),
        ("buy", "5", "60000", SEED_AT - timedelta(days=3), "reconciler", "0007"),
        ("buy", "4", "68000", YESTERDAY, "reconciler", "0000123"),
        ("sell", "3", "71000", TODAY, "reconciler", "0000456"),
        ("sell", "3", "71000", TODAY, "websocket", "456"),
        ("buy", "2", "69000", TODAY + timedelta(hours=1), "websocket", "999"),
        ("buy", "1", "69500", NOW + timedelta(days=1), "manual_import", "M-1"),
    )
    orders = _orders(
        m,
        ("0000456", "filled", "3", TODAY, "sell"),
        ("0000777", "accepted", "2", TODAY, "buy"),
        ("0000778", "partial", "4", TODAY, "sell"),
        ("0000100", "accepted", "1", YESTERDAY, "buy"),
        ("0000101", "pending", "1", YESTERDAY, "sell"),
    )

    def blk(**kw: Any) -> dict[str, Any]:
        args: dict[str, Any] = {
            "symbol": "196170",
            "reference_quantity": Decimal("12"),
            "current_price": Decimal("72000"),
            "fills": base,
            "orders": orders,
            "freshness": fresh,
            "now": NOW,
        }
        args.update(kw)
        return m.build_symbol_block(**args)

    return {
        "known_with_seed_and_evidence": blk(),
        "quantity_mismatch_provisional_pending": blk(reference_quantity=Decimal("14")),
        "stale": blk(freshness=stale),
        "missing": blk(freshness=missing),
        "order_ledger_unreadable": blk(orders=None),
        "no_orders_known": blk(orders=[], fills=base[:4]),
        "reference_missing": blk(reference_quantity=None),
        "reference_zero": blk(reference_quantity=Decimal("0")),
        "no_rows": blk(fills=[], orders=[]),
        "only_provisional": blk(fills=base[4:6]),
        "oversold": blk(
            fills=_fills(
                m,
                ("buy", "1", "100", YESTERDAY, "reconciler", "1"),
                ("sell", "3", "100", TODAY, "reconciler", "2"),
            ),
            reference_quantity=Decimal("1"),
        ),
        "clamped_sellable": blk(
            orders=_orders(m, ("0000999", "accepted", "40", TODAY, "sell")),
            fills=base[:4],
            reference_quantity=Decimal("11"),
        ),
        "open_sell_quantity_missing": blk(
            orders=_orders(m, ("0000999", "accepted", None, TODAY, "sell")),
            fills=base[:4],
            reference_quantity=Decimal("11"),
        ),
        "no_current_price": blk(
            current_price=None,
            fills=base[:4],
            orders=[],
            reference_quantity=Decimal("11"),
        ),
        "unknown_block": m.unknown_block("196170", m.UNKNOWN_LOAD_FAILED),
        "unknown_block_order_read": m.unknown_block(
            "171090", m.UNKNOWN_ORDER_LEDGER_READ_FAILED
        ),
    }


def render(m: ModuleType) -> str:
    return json.dumps(kr_scenarios(m), ensure_ascii=False, indent=1) + "\n"
