version: "3.9"
services:
  db:
    image: postgres:17
    container_name: auto_trader_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auto_trader
    ports: ["5432:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auto_trader"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer
    container_name: adminer
    ports: ["8080:8080"]
    depends_on: [db]

volumes:
  pg_data: