version: "3.9"
services:
  db:
    image: postgres:17
    container_name: auto_trader_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auto_trader
    ports: ["5432:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auto_trader"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - local_dev

  adminer:
    image: adminer
    container_name: adminer
    ports: ["8080:8080"]
    depends_on: 
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - local_dev

  redis:
    image: redis:latest
    container_name: auto_trader_redis
    ports: ["6379:6379"]
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    networks:
      - local_dev

volumes:
  pg_data:
  redis_data:

networks:
  local_dev:
    driver: bridge