"""add news analysis tables

Revision ID: 0d59098a1b34
Revises: c2f3e4b5d6e7
Create Date: 2026-02-10 14:45:19.311633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d59098a1b34'
down_revision: Union[str, Sequence[str], None] = 'c2f3e4b5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False, comment='뉴스 기사 URL'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='뉴스 제목'),
    sa.Column('source', sa.String(length=100), nullable=True, comment='뉴스 출처 (매일경제, 이데일리, etc.)'),
    sa.Column('author', sa.String(length=200), nullable=True, comment='기자명'),
    sa.Column('content', sa.Text(), nullable=False, comment='기사 본문'),
    sa.Column('summary', sa.Text(), nullable=True, comment='기사 요약 (LLM 생성)'),
    sa.Column('stock_symbol', sa.String(length=20), nullable=True, comment='관련 종목 코드 (e.g., 삼성전자)'),
    sa.Column('stock_name', sa.String(length=100), nullable=True, comment='관련 종목명 (e.g., 삼성전자)'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='기사 발행일시'),
    sa.Column('scraped_at', sa.DateTime(), nullable=False, comment='스크래핑 수집일시'),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='데이터 생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='데이터 수정일시'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_news_articles_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_articles')),
    sa.UniqueConstraint('url', name='uq_news_article_url')
    )
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_stock_symbol'), 'news_articles', ['stock_symbol'], unique=False)
    op.create_index(op.f('ix_news_articles_url'), 'news_articles', ['url'], unique=False)
    op.create_index(op.f('ix_news_articles_user_id'), 'news_articles', ['user_id'], unique=False)
    op.create_table('news_analysis_results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False, comment='뉴스 기사 ID'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='사용된 LLM 모델명 (e.g., gemini-2.5-pro)'),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', name='sentiment'), nullable=False, comment='감정 분석 (positive/negative/neutral)'),
    sa.Column('sentiment_score', sa.Float(), nullable=True, comment='감정 점수 (-1.0 ~ 1.0, negative ~ positive)'),
    sa.Column('summary', sa.Text(), nullable=False, comment='기사 요약 (한국어)'),
    sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='핵심 포인트 리스트 (JSON 배열)'),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='주요 키워드/토픽 (JSON 배열)'),
    sa.Column('price_impact', sa.Text(), nullable=True, comment='주가 영향 분석 (한국어)'),
    sa.Column('price_impact_score', sa.Float(), nullable=True, comment='주가 영향 점수 (-1.0 ~ 1.0, negative ~ positive)'),
    sa.Column('confidence', sa.Integer(), nullable=False, comment='분석 신뢰도 (0-100)'),
    sa.Column('analysis_quality', sa.String(length=50), nullable=True, comment='분석 품질 (high/medium/low)'),
    sa.Column('prompt', sa.Text(), nullable=False, comment='LLM에 전달한 프롬프트'),
    sa.Column('raw_response', sa.Text(), nullable=False, comment='LLM 원본 응답'),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True, comment='LLM 처리 시간 (밀리초)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='분석 생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='분석 수정일시'),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], name=op.f('fk_news_analysis_results_article_id_news_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_analysis_results'))
    )
    op.create_index('ix_news_analysis_article_sentiment', 'news_analysis_results', ['article_id', 'sentiment'], unique=False)
    op.create_index(op.f('ix_news_analysis_results_article_id'), 'news_analysis_results', ['article_id'], unique=False)
    op.create_index(op.f('ix_news_analysis_results_sentiment'), 'news_analysis_results', ['sentiment'], unique=False)
    op.create_index('ix_news_analysis_sentiment_created', 'news_analysis_results', ['sentiment', 'created_at'], unique=False)
    op.alter_column('stock_analysis_results', 'stock_info_id',
               existing_type=sa.INTEGER(),
               comment='주식 정보 ID',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment='사용된 AI 모델명',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'decision',
               existing_type=sa.VARCHAR(length=20),
               comment='투자 결정 (buy, hold, sell)',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'confidence',
               existing_type=sa.INTEGER(),
               comment='분석 신뢰도 (0-100)',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'appropriate_buy_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='적절한 매수 범위 최소값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'appropriate_buy_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='적절한 매수 범위 최대값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'appropriate_sell_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='적절한 매도 범위 최소값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'appropriate_sell_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='적절한 매도 범위 최대값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'buy_hope_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='매수 희망 범위 최소값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'buy_hope_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='매수 희망 범위 최대값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'sell_target_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='매도 목표 범위 최소값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'sell_target_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='매도 목표 범위 최대값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'reasons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='분석 근거 (JSON 형태로 저장)',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'detailed_text',
               existing_type=sa.TEXT(),
               comment='상세 분석 텍스트',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'prompt',
               existing_type=sa.TEXT(),
               comment='원본 프롬프트',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_analysis_results', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간',
               existing_nullable=True)
    op.alter_column('stock_info', 'symbol',
               existing_type=sa.VARCHAR(length=50),
               comment='종목 코드/심볼',
               existing_nullable=False)
    op.alter_column('stock_info', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='종목명',
               existing_nullable=False)
    op.alter_column('stock_info', 'instrument_type',
               existing_type=sa.VARCHAR(length=50),
               comment='상품 유형 (equity_kr, equity_us, crypto 등)',
               existing_nullable=False)
    op.alter_column('stock_info', 'exchange',
               existing_type=sa.VARCHAR(length=50),
               comment='거래소',
               existing_nullable=True)
    op.alter_column('stock_info', 'sector',
               existing_type=sa.VARCHAR(length=100),
               comment='섹터/업종',
               existing_nullable=True)
    op.alter_column('stock_info', 'market_cap',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='시가총액',
               existing_nullable=True)
    op.alter_column('stock_info', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='활성화 여부',
               existing_nullable=False)
    op.alter_column('stock_info', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_info', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간',
               existing_nullable=True)
    op.alter_column('user_watch_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('user_watch_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-07 14:12:47.2124+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('user_watch_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-07 14:12:47.2124+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('user_watch_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-07 14:12:47.2124+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('stock_info', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정 시간',
               existing_nullable=True)
    op.alter_column('stock_info', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_info', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='활성화 여부',
               existing_nullable=False)
    op.alter_column('stock_info', 'market_cap',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='시가총액',
               existing_nullable=True)
    op.alter_column('stock_info', 'sector',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='섹터/업종',
               existing_nullable=True)
    op.alter_column('stock_info', 'exchange',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='거래소',
               existing_nullable=True)
    op.alter_column('stock_info', 'instrument_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='상품 유형 (equity_kr, equity_us, crypto 등)',
               existing_nullable=False)
    op.alter_column('stock_info', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='종목명',
               existing_nullable=False)
    op.alter_column('stock_info', 'symbol',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='종목 코드/심볼',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정 시간',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_analysis_results', 'prompt',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='원본 프롬프트',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'detailed_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='상세 분석 텍스트',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'reasons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='분석 근거 (JSON 형태로 저장)',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'sell_target_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='매도 목표 범위 최대값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'sell_target_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='매도 목표 범위 최소값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'buy_hope_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='매수 희망 범위 최대값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'buy_hope_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='매수 희망 범위 최소값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'appropriate_sell_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='적절한 매도 범위 최대값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'appropriate_sell_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='적절한 매도 범위 최소값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'appropriate_buy_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='적절한 매수 범위 최대값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'appropriate_buy_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='적절한 매수 범위 최소값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'confidence',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='분석 신뢰도 (0-100)',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'decision',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='투자 결정 (buy, hold, sell)',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='사용된 AI 모델명',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'stock_info_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='주식 정보 ID',
               existing_nullable=False)
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nickname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tz', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('base_currency', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('admin', 'trader', 'viewer', name='user_role'), autoincrement=False, nullable=True)
    )
    op.drop_index('ix_news_analysis_sentiment_created', table_name='news_analysis_results')
    op.drop_index(op.f('ix_news_analysis_results_sentiment'), table_name='news_analysis_results')
    op.drop_index(op.f('ix_news_analysis_results_article_id'), table_name='news_analysis_results')
    op.drop_index('ix_news_analysis_article_sentiment', table_name='news_analysis_results')
    op.drop_table('news_analysis_results')
    op.drop_index(op.f('ix_news_articles_user_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_url'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_stock_symbol'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
