"""rob920_alpaca_canceled

Revision ID: 20260717_rob920_alpaca_canceled
Revises: 20260714_rob850_paper_evaluation
Create Date: 2026-07-17 02:16:48

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260717_rob920_alpaca_canceled'
down_revision: str | Sequence[str] | None = '20260714_rob850_paper_evaluation'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop legacy autogenerated constraint if it exists
    op.execute(
        "ALTER TABLE review.alpaca_paper_order_ledger "
        "DROP CONSTRAINT IF EXISTS ck_alpaca_paper_order_ledger_alpaca_paper_ledger_lifecy_dbbd"
    )
    # Drop official constraint
    op.execute(
        "ALTER TABLE review.alpaca_paper_order_ledger "
        "DROP CONSTRAINT IF EXISTS alpaca_paper_ledger_lifecycle_state"
    )
    # Recreate the check constraint with 'canceled' included
    op.create_check_constraint(
        "alpaca_paper_ledger_lifecycle_state",
        "alpaca_paper_order_ledger",
        "lifecycle_state IN ('planned','previewed','validated','submitted','filled',"
        "'position_reconciled','sell_validated','closed','final_reconciled','anomaly',"
        "'stale_preview_cleanup_required','canceled')",
        schema="review",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Map 'canceled' to 'anomaly' before restoring the old CHECK constraint
    op.execute(
        "UPDATE review.alpaca_paper_order_ledger "
        "SET lifecycle_state = 'anomaly', "
        "    error_summary = COALESCE(error_summary, 'Downgraded from canceled') "
        "WHERE lifecycle_state = 'canceled'"
    )
    # Drop legacy autogenerated constraint if it exists
    op.execute(
        "ALTER TABLE review.alpaca_paper_order_ledger "
        "DROP CONSTRAINT IF EXISTS ck_alpaca_paper_order_ledger_alpaca_paper_ledger_lifecy_dbbd"
    )
    # Drop official constraint
    op.execute(
        "ALTER TABLE review.alpaca_paper_order_ledger "
        "DROP CONSTRAINT IF EXISTS alpaca_paper_ledger_lifecycle_state"
    )
    op.create_check_constraint(
        "alpaca_paper_ledger_lifecycle_state",
        "alpaca_paper_order_ledger",
        "lifecycle_state IN ('planned','previewed','validated','submitted','filled',"
        "'position_reconciled','sell_validated','closed','final_reconciled','anomaly',"
        "'stale_preview_cleanup_required')",
        schema="review",
    )
