"""rob306 investment_dimension_reports

Revision ID: 38d4f86503b1
Revises: 20260523_rob301_p1
Create Date: 2026-05-24 14:49:47.283689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38d4f86503b1'
down_revision: Union[str, Sequence[str], None] = '20260523_rob301_p1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_dimension_reports',
    sa.Column('id', sa.BigInteger(), nullable=False, autoincrement=True),
    sa.Column('dimension_report_uuid', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('snapshot_bundle_uuid', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.Text(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('account_scope', sa.Text(), nullable=True),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('artifact_version', sa.Integer(), nullable=False, server_default=sa.text('1')),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('key_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stance', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('missing_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('freshness_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('cited_snapshot_uuids', sa.ARRAY(sa.UUID()), nullable=False, server_default=sa.text("ARRAY[]::uuid[]")),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
    sa.ForeignKeyConstraint(['run_uuid'], ['review.investment_stage_runs.run_uuid'], name=op.f('fk_investment_dimension_reports_run_uuid_investment_stage_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investment_dimension_reports')),
    sa.UniqueConstraint('dimension_report_uuid', name='uq_investment_dimension_reports_dimension_report_uuid'),
    sa.UniqueConstraint('idempotency_key', name='uq_investment_dimension_reports_idempotency_key'),
    sa.UniqueConstraint('run_uuid', 'dimension', 'market', 'symbol', 'artifact_version', name='uq_investment_dimension_reports_run_dim_market_symbol_ver'),
    sa.CheckConstraint("dimension IN ('market', 'news', 'fundamentals', 'sentiment')", name='ck_investment_dimension_reports_dimension'),
    sa.CheckConstraint("market IN ('kr', 'us', 'crypto')", name='ck_investment_dimension_reports_market'),
    sa.CheckConstraint("stance IS NULL OR stance IN ('bullish', 'neutral', 'bearish')", name='ck_investment_dimension_reports_stance'),
    sa.CheckConstraint("confidence IS NULL OR (confidence >= 0 AND confidence <= 100)", name='ck_investment_dimension_reports_confidence_range'),
    schema='review'
    )
    op.create_index('ix_investment_dimension_reports_run_uuid', 'investment_dimension_reports', ['run_uuid'], unique=False, schema='review')
    op.create_index('ix_investment_dimension_reports_run_dimension', 'investment_dimension_reports', ['run_uuid', 'dimension'], unique=False, schema='review')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_investment_dimension_reports_run_dimension', table_name='investment_dimension_reports', schema='review')
    op.drop_index('ix_investment_dimension_reports_run_uuid', table_name='investment_dimension_reports', schema='review')
    op.drop_table('investment_dimension_reports', schema='review')
    # ### end Alembic commands ###
