"""fix timestamp defaults

Revision ID: 566682e4e76e
Revises: ecec144111c6
Create Date: 2025-08-15 08:05:13.480448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '566682e4e76e'
down_revision: Union[str, Sequence[str], None] = 'ecec144111c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompt_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('prompt_results', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('user_watch_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('user_watch_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-08-14 15:40:35.062877+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('user_watch_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-08-14 15:40:35.062877+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('user_watch_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-08-14 15:40:35.062877+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('prompt_results', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-08-14 15:40:35.062877+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('prompt_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-08-14 15:40:35.062877+00'::timestamp with time zone"),
               existing_nullable=False)
    # ### end Alembic commands ###
