"""add_manual_holdings_and_broker_accounts

Revision ID: 7cff05b5aa4d
Revises: d6ed88375237
Create Date: 2025-12-01 15:54:37.664660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cff05b5aa4d'
down_revision: Union[str, Sequence[str], None] = 'd6ed88375237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_aliases',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('market_type', sa.Enum('KR', 'US', 'CRYPTO', name='market_type'), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_aliases')),
    sa.UniqueConstraint('alias', 'market_type', name='uq_alias_market')
    )
    op.create_index(op.f('ix_stock_aliases_alias'), 'stock_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_stock_aliases_ticker'), 'stock_aliases', ['ticker'], unique=False)
    op.create_table('broker_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('broker_type', sa.Enum('kis', 'toss', 'upbit', name='broker_type'), nullable=False),
    sa.Column('account_name', sa.Text(), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_broker_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broker_accounts')),
    sa.UniqueConstraint('user_id', 'broker_type', 'account_name', name='uq_broker_account')
    )
    op.create_index(op.f('ix_broker_accounts_user_id'), 'broker_accounts', ['user_id'], unique=False)
    op.create_table('manual_holdings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('broker_account_id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('market_type', sa.Enum('KR', 'US', 'CRYPTO', name='market_type'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], name=op.f('fk_manual_holdings_broker_account_id_broker_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_holdings')),
    sa.UniqueConstraint('broker_account_id', 'ticker', 'market_type', name='uq_holding_ticker')
    )
    op.create_index(op.f('ix_manual_holdings_broker_account_id'), 'manual_holdings', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_manual_holdings_ticker'), 'manual_holdings', ['ticker'], unique=False)
    op.alter_column('user_watch_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('user_watch_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-11-28 23:35:38.363215+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('user_watch_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-11-28 23:35:38.363215+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('user_watch_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-11-28 23:35:38.363215+00'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_index(op.f('ix_manual_holdings_ticker'), table_name='manual_holdings')
    op.drop_index(op.f('ix_manual_holdings_broker_account_id'), table_name='manual_holdings')
    op.drop_table('manual_holdings')
    op.drop_index(op.f('ix_broker_accounts_user_id'), table_name='broker_accounts')
    op.drop_table('broker_accounts')
    op.drop_index(op.f('ix_stock_aliases_ticker'), table_name='stock_aliases')
    op.drop_index(op.f('ix_stock_aliases_alias'), table_name='stock_aliases')
    op.drop_table('stock_aliases')
    # ### end Alembic commands ###
