"""add user_trade_defaults and update symbol_trade_settings with user_id

Revision ID: a135dbde152e
Revises: a69eac660fba
Create Date: 2025-11-29 08:35:13.237250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a135dbde152e'
down_revision: Union[str, Sequence[str], None] = 'a69eac660fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_trade_defaults',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('crypto_default_buy_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('crypto_min_order_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('equity_kr_default_buy_quantity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('equity_us_default_buy_quantity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('equity_us_default_buy_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_trade_defaults_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_trade_defaults'))
    )
    op.create_index(op.f('ix_user_trade_defaults_user_id'), 'user_trade_defaults', ['user_id'], unique=True)
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)

    # Add user_id column as nullable first
    op.add_column('symbol_trade_settings', sa.Column('user_id', sa.BigInteger(), nullable=True))

    # Drop old unique index on symbol before duplicating rows per user
    op.drop_index(op.f('ix_symbol_trade_settings_symbol'), table_name='symbol_trade_settings')

    bind = op.get_bind()
    user_ids = [row[0] for row in bind.execute(sa.text("SELECT id FROM users")).fetchall()]
    has_settings = bool(bind.execute(sa.text("SELECT COUNT(*) FROM symbol_trade_settings")).scalar())

    if has_settings:
        if user_ids:
            # 기존 설정을 모든 사용자에게 복제해 데이터 손실을 방지
            for user_id in user_ids:
                bind.execute(
                    sa.text(
                        """
                        INSERT INTO symbol_trade_settings (
                            symbol,
                            instrument_type,
                            buy_quantity_per_order,
                            buy_price_levels,
                            exchange_code,
                            is_active,
                            note,
                            created_at,
                            updated_at,
                            user_id
                        )
                        SELECT
                            symbol,
                            instrument_type,
                            buy_quantity_per_order,
                            buy_price_levels,
                            exchange_code,
                            is_active,
                            note,
                            created_at,
                            updated_at,
                            :user_id
                        FROM symbol_trade_settings
                        WHERE user_id IS NULL
                        """
                    ),
                    {"user_id": user_id},
                )
        else:
            # 연결된 사용자가 없으면 기존 설정을 정리해 제약 조건 위반을 방지
            bind.execute(sa.text("DELETE FROM symbol_trade_settings"))

    # 기존 null user_id 행 제거
    bind.execute(sa.text("DELETE FROM symbol_trade_settings WHERE user_id IS NULL"))

    # Now make the column non-nullable
    op.alter_column('symbol_trade_settings', 'user_id', nullable=False)
    op.alter_column('symbol_trade_settings', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_symbol_trade_settings_symbol'), 'symbol_trade_settings', ['symbol'], unique=False)
    op.create_index(op.f('ix_symbol_trade_settings_user_id'), 'symbol_trade_settings', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_symbol', 'symbol_trade_settings', ['user_id', 'symbol'])
    op.create_foreign_key(op.f('fk_symbol_trade_settings_user_id_users'), 'symbol_trade_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_watch_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('user_watch_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-11-22 12:18:56.826404+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('user_watch_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-11-22 12:18:56.826404+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('user_watch_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-11-22 12:18:56.826404+00'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_symbol_trade_settings_user_id_users'), 'symbol_trade_settings', type_='foreignkey')
    op.drop_constraint('uq_user_symbol', 'symbol_trade_settings', type_='unique')
    op.drop_index(op.f('ix_symbol_trade_settings_user_id'), table_name='symbol_trade_settings')
    op.drop_index(op.f('ix_symbol_trade_settings_symbol'), table_name='symbol_trade_settings')

    # 복제된 설정이 있을 수 있으므로 심볼 기준 중복을 제거한 후 기존 제약을 복원
    op.execute(
        """
        DELETE FROM symbol_trade_settings s
        USING symbol_trade_settings dup
        WHERE s.id > dup.id
          AND s.symbol = dup.symbol
        """
    )

    op.create_index(op.f('ix_symbol_trade_settings_symbol'), 'symbol_trade_settings', ['symbol'], unique=True)
    op.alter_column('symbol_trade_settings', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('symbol_trade_settings', 'user_id')
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_trade_defaults_user_id'), table_name='user_trade_defaults')
    op.drop_table('user_trade_defaults')
    # ### end Alembic commands ###
