"""Add authentication fields to User model

Revision ID: bb51ac8d080c
Revises: modify_stock_analysis
Create Date: 2025-11-19 08:31:11.895636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb51ac8d080c'
down_revision: Union[str, Sequence[str], None] = 'modify_stock_analysis'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First drop the foreign key constraint
    op.drop_constraint(op.f('fk_user_watch_items_broker_account_id_broker_accounts'), 'user_watch_items', type_='foreignkey')
    op.drop_column('user_watch_items', 'broker_account_id')
    # Now we can safely drop the broker_accounts table
    op.drop_table('broker_accounts')
    op.alter_column('user_watch_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('user_watch_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.add_column('users', sa.Column('username', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.Text(), nullable=True))
    # Add is_active as nullable first, then set default and make NOT NULL
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE users SET is_active = true WHERE is_active IS NULL")
    # Now make it NOT NULL
    op.alter_column('users', 'is_active', nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-11-01 08:28:08.387703+00'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'username')
    op.add_column('user_watch_items', sa.Column('broker_account_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_user_watch_items_broker_account_id_broker_accounts'), 'user_watch_items', 'broker_accounts', ['broker_account_id'], ['id'])
    op.alter_column('user_watch_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-11-01 08:28:08.387703+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('user_watch_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-11-01 08:28:08.387703+00'::timestamp with time zone"),
               existing_nullable=False)
    op.create_table('broker_accounts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('broker_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('broker_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('account_no', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_mock', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-11-01 08:28:08.387703+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-11-01 08:28:08.387703+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_broker_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broker_accounts'))
    )
    # ### end Alembic commands ###
