"""create stock analysis table

Revision ID: create_stock_analysis_table
Revises: 566682e4e76e
Create Date: 2024-12-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'stock_analysis_table'
down_revision = 'stock_info_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('instrument_type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('appropriate_buy_min', sa.Float(), nullable=True),
    sa.Column('appropriate_buy_max', sa.Float(), nullable=True),
    sa.Column('appropriate_sell_min', sa.Float(), nullable=True),
    sa.Column('appropriate_sell_max', sa.Float(), nullable=True),
    sa.Column('buy_hope_min', sa.Float(), nullable=True),
    sa.Column('buy_hope_max', sa.Float(), nullable=True),
    sa.Column('sell_target_min', sa.Float(), nullable=True),
    sa.Column('sell_target_max', sa.Float(), nullable=True),
    sa.Column('reasons', sa.Text(), nullable=True),
    sa.Column('detailed_text', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_analysis_results_symbol'), 'stock_analysis_results', ['symbol'], unique=False)
    op.create_index(op.f('ix_stock_analysis_results_id'), 'stock_analysis_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_analysis_results_id'), table_name='stock_analysis_results')
    op.drop_index(op.f('ix_stock_analysis_results_symbol'), table_name='stock_analysis_results')
    op.drop_table('stock_analysis_results')
    # ### end Alembic commands ###
