"""Add role field to User model

Revision ID: e09d5eb2e49f
Revises: bb51ac8d080c
Create Date: 2025-11-22 21:18:22.255206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e09d5eb2e49f'
down_revision: Union[str, Sequence[str], None] = 'bb51ac8d080c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_watch_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('user_watch_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    # Create enum type first
    user_role_enum = postgresql.ENUM('admin', 'trader', 'viewer', name='user_role', create_type=True)
    user_role_enum.create(op.get_bind(), checkfirst=True)

    # First add the role column as nullable
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'trader', 'viewer', name='user_role'), nullable=True))
    # Set default role for existing users
    op.execute("UPDATE users SET role = 'viewer' WHERE role IS NULL")
    # Now make it NOT NULL
    op.alter_column('users', 'role', nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-11-18 23:31:50.13892+00'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_column('users', 'role')
    op.alter_column('user_watch_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-11-18 23:31:50.13892+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('user_watch_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-11-18 23:31:50.13892+00'::timestamp with time zone"),
               existing_nullable=False)
    # ### end Alembic commands ###
