"""add broker_accounts table and update schema

Revision ID: ecac55ddc9b1
Revises: modify_stock_analysis
Create Date: 2025-11-01 17:27:57.788624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecac55ddc9b1'
down_revision: Union[str, Sequence[str], None] = 'modify_stock_analysis'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('broker_type', sa.Text(), nullable=False),
    sa.Column('broker_name', sa.Text(), nullable=False),
    sa.Column('account_no', sa.Text(), nullable=True),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_broker_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broker_accounts'))
    )
    op.alter_column('stock_analysis_results', 'stock_info_id',
               existing_type=sa.INTEGER(),
               comment='주식 정보 ID',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment='사용된 AI 모델명',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'decision',
               existing_type=sa.VARCHAR(length=20),
               comment='투자 결정 (buy, hold, sell)',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'confidence',
               existing_type=sa.INTEGER(),
               comment='분석 신뢰도 (0-100)',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'appropriate_buy_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='적절한 매수 범위 최소값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'appropriate_buy_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='적절한 매수 범위 최대값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'appropriate_sell_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='적절한 매도 범위 최소값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'appropriate_sell_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='적절한 매도 범위 최대값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'buy_hope_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='매수 희망 범위 최소값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'buy_hope_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='매수 희망 범위 최대값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'sell_target_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='매도 목표 범위 최소값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'sell_target_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='매도 목표 범위 최대값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'reasons',
               existing_type=sa.TEXT(),
               comment='분석 근거 (JSON 형태로 저장)',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'detailed_text',
               existing_type=sa.TEXT(),
               comment='상세 분석 텍스트',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'prompt',
               existing_type=sa.TEXT(),
               comment='원본 프롬프트',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_analysis_results', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간',
               existing_nullable=True)
    op.alter_column('stock_info', 'symbol',
               existing_type=sa.VARCHAR(length=50),
               comment='종목 코드/심볼',
               existing_nullable=False)
    op.alter_column('stock_info', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='종목명',
               existing_nullable=False)
    op.alter_column('stock_info', 'instrument_type',
               existing_type=sa.VARCHAR(length=50),
               comment='상품 유형 (equity_kr, equity_us, crypto 등)',
               existing_nullable=False)
    op.alter_column('stock_info', 'exchange',
               existing_type=sa.VARCHAR(length=50),
               comment='거래소',
               existing_nullable=True)
    op.alter_column('stock_info', 'sector',
               existing_type=sa.VARCHAR(length=100),
               comment='섹터/업종',
               existing_nullable=True)
    op.alter_column('stock_info', 'market_cap',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='시가총액',
               existing_nullable=True)
    op.alter_column('stock_info', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='활성화 여부',
               existing_nullable=False)
    op.alter_column('stock_info', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_info', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간',
               existing_nullable=True)
    op.add_column('user_watch_items', sa.Column('broker_account_id', sa.BigInteger(), nullable=True))
    op.alter_column('user_watch_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('user_watch_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_user_watch_items_broker_account_id_broker_accounts'), 'user_watch_items', 'broker_accounts', ['broker_account_id'], ['id'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-08-15 12:52:27.131355+00'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_user_watch_items_broker_account_id_broker_accounts'), 'user_watch_items', type_='foreignkey')
    op.alter_column('user_watch_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-08-15 12:52:27.131355+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('user_watch_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-08-15 12:52:27.131355+00'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_column('user_watch_items', 'broker_account_id')
    op.alter_column('stock_info', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정 시간',
               existing_nullable=True)
    op.alter_column('stock_info', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_info', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='활성화 여부',
               existing_nullable=False)
    op.alter_column('stock_info', 'market_cap',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='시가총액',
               existing_nullable=True)
    op.alter_column('stock_info', 'sector',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='섹터/업종',
               existing_nullable=True)
    op.alter_column('stock_info', 'exchange',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='거래소',
               existing_nullable=True)
    op.alter_column('stock_info', 'instrument_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='상품 유형 (equity_kr, equity_us, crypto 등)',
               existing_nullable=False)
    op.alter_column('stock_info', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='종목명',
               existing_nullable=False)
    op.alter_column('stock_info', 'symbol',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='종목 코드/심볼',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정 시간',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_analysis_results', 'prompt',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='원본 프롬프트',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'detailed_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='상세 분석 텍스트',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'reasons',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='분석 근거 (JSON 형태로 저장)',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'sell_target_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='매도 목표 범위 최대값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'sell_target_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='매도 목표 범위 최소값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'buy_hope_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='매수 희망 범위 최대값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'buy_hope_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='매수 희망 범위 최소값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'appropriate_sell_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='적절한 매도 범위 최대값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'appropriate_sell_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='적절한 매도 범위 최소값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'appropriate_buy_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='적절한 매수 범위 최대값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'appropriate_buy_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='적절한 매수 범위 최소값',
               existing_nullable=True)
    op.alter_column('stock_analysis_results', 'confidence',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='분석 신뢰도 (0-100)',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'decision',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='투자 결정 (buy, hold, sell)',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='사용된 AI 모델명',
               existing_nullable=False)
    op.alter_column('stock_analysis_results', 'stock_info_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='주식 정보 ID',
               existing_nullable=False)
    op.drop_table('broker_accounts')
    # ### end Alembic commands ###
