"""ROB-373 — Claude Code schedule entrypoint for US /invest/reports.

Default-disabled operator runner. Collects common evidence once, then produces a
kis_live advisory report and a kis_mock mock_preview report (the latter via the
ROB-373 mock runner). NO live order execution, NO market orders, NO shorting.
Only KIS_MOCK_* / KIS live creds present in the schedule environment are used;
``.env.prod.native`` is never sourced wholesale.

Modes (mutually exclusive):
  --dry-run : print the planned sequence; no HTTP, no DB, no secrets required.
  --run     : execute live advisory generation + mock_preview runner.
  (no flag) : enabled-no-action guidance.

Exit codes:
  0 — disabled, dry-run, guidance, or successful run
  1 — unexpected exception during --run
  2 — misconfiguration (e.g. --kst-date missing)
  3 — live advisory generation failed
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import os
import sys
import uuid

logger = logging.getLogger("invest_reports_us_schedule")

_ENABLE_ENV = "INVEST_REPORTS_US_SCHEDULE_ENABLED"
_MARKET = "us"


def _truthy(value: str | None) -> bool:
    return (value or "").strip().lower() in {"1", "true", "yes", "on"}


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "ROB-373 US /invest/reports schedule runner. Default-disabled "
            f"(set {_ENABLE_ENV}=true to opt in). Produces a kis_live advisory "
            "report and a kis_mock mock_preview report from shared evidence. "
            "No live order execution / market orders / shorting."
        )
    )
    mode = parser.add_mutually_exclusive_group(required=False)
    mode.add_argument(
        "--dry-run",
        dest="dry_run",
        action="store_true",
        help="Print the planned sequence without side effects (no creds needed).",
    )
    mode.add_argument(
        "--run",
        action="store_true",
        help="Execute live advisory generation + mock_preview runner.",
    )
    parser.add_argument("--market-session", default="regular")
    parser.add_argument("--kst-date", default=None, help="KST date YYYY-MM-DD.")
    parser.add_argument(
        "--policy-version", default="intraday_action_report_v1"
    )
    parser.add_argument("--created-by-profile", default="schedule")
    parser.add_argument("--log-level", default="INFO")
    return parser.parse_args(argv)


_PLAN_LINES = (
    "1. prepare_bundle(market=us)  -> shared NULL-scope evidence collected once",
    "2. generate live report       -> account_scope=kis_live, execution_mode=advisory_only",
    "3. mock_preview runner         -> account_scope=kis_mock, execution_mode=mock_preview",
    "4. mock preview bridge         -> invoked per BUY item inside step 3 (KIS-mock read-only, submit OFF, no Alpaca)",
)


def _print_plan() -> None:
    print("ROB-373 US schedule plan (dry-run, no side effects):")
    for line in _PLAN_LINES:
        print("  " + line)


async def _run(args: argparse.Namespace) -> int:
    # Lazy imports: keep --help / --dry-run / disabled path free of Settings+DB.
    from app.core.db import AsyncSessionLocal  # noqa: PLC0415
    from app.mcp_server.tooling.investment_reports_handlers import (  # noqa: PLC0415
        investment_report_generate_from_bundle_impl,
    )
    from app.services.investment_reports.mock_preview.runner import (  # noqa: PLC0415
        MockPreviewReportRunner,
    )

    kst_date = args.kst_date
    if kst_date is None:
        logger.error("--kst-date is required for --run")
        return 2

    live_result = await investment_report_generate_from_bundle_impl(
        market=_MARKET,
        account_scope="kis_live",
        market_session=args.market_session,
        kst_date=kst_date,
        created_by_profile=args.created_by_profile,
        policy_version=args.policy_version,
        title=f"US Advisory Report {kst_date}",
        summary="Automated US advisory report generated by ROB-373 schedule runner.",
    )
    if not live_result.get("success"):
        logger.error("live generation failed: %s", live_result.get("error"))
        return 3
    live_uuid = live_result["report_uuid"]
    logger.info("live advisory report: %s", live_uuid)

    async with AsyncSessionLocal() as session:
        runner = MockPreviewReportRunner(session)
        report, reused, count = await runner.run(
            live_report_uuid=uuid.UUID(str(live_uuid)),
            market=_MARKET,
            market_session=args.market_session,
            policy_version=args.policy_version,
            kst_date=kst_date,
            created_by_profile=args.created_by_profile,
        )
        await session.commit()
    logger.info(
        "mock_preview report: %s (reused=%s, items=%s)",
        report.report_uuid,
        reused,
        count,
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    logging.basicConfig(level=getattr(logging, args.log_level.upper(), logging.INFO))

    # Gate AFTER argparse (so --help works) but BEFORE any side effect.
    if not _truthy(os.environ.get(_ENABLE_ENV)):
        print(f"{_MARKET} schedule disabled — set {_ENABLE_ENV}=true to opt in")
        return 0

    if args.dry_run:
        _print_plan()
        return 0
    if args.run:
        try:
            return asyncio.run(_run(args))
        except Exception:  # noqa: BLE001
            logger.exception("US schedule run failed")
            return 1

    print(
        "enabled but no action requested. Pass --dry-run to print the plan or "
        "--run to generate live advisory + mock_preview reports."
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main(sys.argv[1:]))
