"""Investment symbol-scoped intermediate reports ORM (ROB-301).

Per-symbol intermediate reports: a durable, auditable reduction over per-symbol
snapshots + cross-symbol stage artifacts. Generated by Hermes out-of-process
(pull -> compose -> push), then validated and persisted here. Final report
composition consumes these via a ``report.metadata`` reference.

Axis note
---------
Distinct table from ``investment_stage_artifacts``. Stage artifacts live on the
analysis-DIMENSION axis (UNIQUE(run_uuid, stage_type) — market/news/risk/...).
This table lives on the SYMBOL axis:

    UNIQUE(run_uuid, symbol, report_kind, artifact_version)

A symbol report belongs to the SAME ``investment_stage_runs`` run (real FK), is
generated after the cross-symbol stage artifacts, and consumes them.
"""

from __future__ import annotations

import datetime as dt
import uuid
from typing import Any

from sqlalchemy import (
    ARRAY,
    BigInteger,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base

# --- Single source of truth for the controlled vocabularies (ROB-301 D5). ---
# The DB CHECK constraints below are BUILT from these tuples, and the Pydantic
# schema Literals (PR T2) import the same tuples. The three layers therefore
# cannot drift; ``tests/models/test_investment_symbol_intermediate_reports_model.py``
# asserts the model CHECK reflects each tuple value.
DECISION_BUCKETS: tuple[str, ...] = (
    "new_buy_candidate",
    "open_action",
    "completed_or_existing",
    "deferred_no_action",
    "risk_watch",
)
VERDICTS: tuple[str, ...] = ("buy", "sell", "hold", "risk", "unavailable")
UNAVAILABLE_REASONS: tuple[str, ...] = ("hermes_omitted", "data_unavailable")
REPORT_KINDS: tuple[str, ...] = ("final_report_symbol",)
# account_scope reuses the existing investment_reports vocabulary (no new terms).
ACCOUNT_SCOPES: tuple[str, ...] = (
    "kis_live",
    "kis_mock",
    "alpaca_paper",
    "upbit_live",
)


def _sql_in(values: tuple[str, ...]) -> str:
    """Render a tuple as a SQL IN-list literal: ('a','b')."""
    return ", ".join(f"'{v}'" for v in values)


class InvestmentSymbolIntermediateReport(Base):
    __tablename__ = "investment_symbol_intermediate_reports"
    __table_args__ = (
        CheckConstraint(
            f"decision_bucket IN ({_sql_in(DECISION_BUCKETS)})",
            name="ck_investment_symbol_intermediate_reports_decision_bucket",
        ),
        CheckConstraint(
            f"verdict IN ({_sql_in(VERDICTS)})",
            name="ck_investment_symbol_intermediate_reports_verdict",
        ),
        CheckConstraint(
            "unavailable_reason IS NULL OR unavailable_reason IN "
            f"({_sql_in(UNAVAILABLE_REASONS)})",
            name="ck_investment_symbol_intermediate_reports_unavailable_reason",
        ),
        CheckConstraint(
            f"report_kind IN ({_sql_in(REPORT_KINDS)})",
            name="ck_investment_symbol_intermediate_reports_report_kind",
        ),
        CheckConstraint(
            f"account_scope IS NULL OR account_scope IN ({_sql_in(ACCOUNT_SCOPES)})",
            name="ck_investment_symbol_intermediate_reports_account_scope",
        ),
        CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 100)",
            name="ck_investment_symbol_intermediate_reports_confidence_range",
        ),
        # ROB-301 D11: an unavailable verdict must pin the deferred_no_action
        # bucket (no separate unavailable bucket — keep the 5-value set).
        CheckConstraint(
            "verdict <> 'unavailable' OR decision_bucket = 'deferred_no_action'",
            name="ck_investment_symbol_intermediate_reports_unavailable_bucket",
        ),
        UniqueConstraint(
            "run_uuid",
            "symbol",
            "report_kind",
            "artifact_version",
            name="uq_investment_symbol_intermediate_reports_run_symbol_kind_ver",
        ),
        Index("ix_investment_symbol_intermediate_reports_run_uuid", "run_uuid"),
        Index("ix_investment_symbol_intermediate_reports_symbol", "symbol"),
        Index(
            "ix_investment_symbol_intermediate_reports_bundle_uuid",
            "snapshot_bundle_uuid",
        ),
        {"schema": "review"},
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    symbol_report_uuid: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        nullable=False,
        unique=True,
        server_default=text("gen_random_uuid()"),
    )
    # Real FK to the owning stage run (ROB-301 D11): a symbol report belongs to
    # the same run as the cross-symbol stage artifacts it consumes.
    run_uuid: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("review.investment_stage_runs.run_uuid", ondelete="CASCADE"),
        nullable=False,
    )
    # Run-level bundle; always present even for evidence-less symbols.
    snapshot_bundle_uuid: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True), nullable=False
    )
    market: Mapped[str] = mapped_column(Text, nullable=False)
    account_scope: Mapped[str | None] = mapped_column(Text, nullable=True)
    symbol: Mapped[str] = mapped_column(Text, nullable=False)
    symbol_name: Mapped[str | None] = mapped_column(Text, nullable=True)
    report_kind: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=text("'final_report_symbol'")
    )
    artifact_version: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("1")
    )
    # Operator-facing first-class classifier (5-value set).
    decision_bucket: Mapped[str] = mapped_column(Text, nullable=False)
    # Service-derived signal direction (caller-provided value is rejected).
    verdict: Mapped[str] = mapped_column(Text, nullable=False)
    # Distinguishes Hermes-omitted vs data-genuinely-unavailable (ROB-301 D11).
    unavailable_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    confidence: Mapped[int | None] = mapped_column(Integer, nullable=True)
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    rationale: Mapped[str | None] = mapped_column(Text, nullable=True)
    buy_evidence: Mapped[list[Any] | None] = mapped_column(JSONB, nullable=True)
    sell_evidence: Mapped[list[Any] | None] = mapped_column(JSONB, nullable=True)
    risk_evidence: Mapped[list[Any] | None] = mapped_column(JSONB, nullable=True)
    missing_data: Mapped[list[Any] | None] = mapped_column(JSONB, nullable=True)
    freshness_summary: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB, nullable=True
    )
    # Canonical payload hash — drives idempotent upsert + version bump (D11).
    content_hash: Mapped[str] = mapped_column(Text, nullable=False)
    source_stage_artifact_uuids: Mapped[list[uuid.UUID]] = mapped_column(
        ARRAY(PG_UUID(as_uuid=True)),
        nullable=False,
        server_default=text("ARRAY[]::uuid[]"),
    )
    cited_snapshot_uuids: Mapped[list[uuid.UUID]] = mapped_column(
        ARRAY(PG_UUID(as_uuid=True)),
        nullable=False,
        server_default=text("ARRAY[]::uuid[]"),
    )
    # = run_uuid:symbol:report_kind:content_hash (built by the service).
    idempotency_key: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
